# Generated by Django 3.2.19 on 2023-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('new_home_needed', 'New home needed'), ('tip', 'Tip'), ('help_needed', 'Help needed'), ('other', 'Other')], max_length=32),
        ),
    ]
