# Generated by Django 3.2.19 on 2023-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.CharField(blank=True, choices=[('female_not_spayed', 'Female, not spayed'), ('female_spayed', 'Female, spayed'), ('male_not_neutered', 'Male, not neutered'), ('male, neutered', 'Male, neutered')], max_length=32),
        ),
    ]
