# Generated by Django 3.2.19 on 2023-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sex',
        ),
    ]
