# Generated by Django 3.2.19 on 2023-07-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('adoptionrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='adoption_owner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_owner', to='profiles.profile'),
        ),
    ]
